### ISSUE TITLE
User Story : Home section of the website

### ISSUE THREAD

**Issue by Shaga-Matula** [Shaga-Matula/blue-pulse-band#1]
As a new visitor, I want to access the Home section of the website to learn about the band and their latest news.

## Estimation  Effort (Fibonacci sequence) :
- [ ] <label><input type="checkbox" disabled /> 1 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 2 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 3 Hour </label>
- [x] <label><input type="checkbox" disabled /> 5 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 8 Hour </label>
- [ ] <label><input type="checkbox" disabled /> 13 Hour </label>

## Tasks :
- [x] <label><input type="checkbox" disabled /> Task 1 : Create Basic Site in Django</label>
- [x] <label><input type="checkbox" disabled /> Task 2 : Render A Home Page</label>
- [x] <label><input type="checkbox" disabled /> Task 3 : Render a Base.Html with Navigation Bar </label>

## Acceptance Criteria :
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Home Page Displays with Navigation bar </label>
- [x] <label><input type="checkbox" disabled /> Criteria 1 :  Home Page Link, Home Page, CSS and Image Display in Heroku</label>

**Comment by Shaga-Matula** [comment]
This User Story covers site creation and home page view with access to Heroku

**Comment by VidyaYadavv1519** [comment]
hii, Can you assign me this issue ??

**Comment by Shaga-Matula** [comment]
Sorry I shared it by mistake im on PP5
